version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cicd  # Change this to your application directory
    overwrite: true
    ignore:
      - ".gitignore"
 

hooks:
  BeforeInstall:
  - location: scripts/clean_deployment_directory.sh
    timeout: 300
    runas: root
  - location: scripts/install_dependencies.sh
    timeout: 300
    runas: root

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_node_app.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: scripts/stop_node_app.sh
      timeout: 300
      runas: ec2-user
